# Generated by Django 3.1.2 on 2020-10-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purple', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://image.shutterstock.com/image-illustration/colourful-business-logo-company-name-260nw-1779060338.jpg', max_length=500),
        ),
    ]
